### ISSUE TITLE
groovy script for creating a new ldap connection

### ISSUE THREAD

**Issue by gajendra4278** [sonatype/nexus-book#238]
groovy script for creating a new ldap connection for NEXUS OSS 3.x.x

**Comment by DarthHater** [comment]
Hi there, mind explaining exactly what you are trying to accomplish? The issue is a bit vague at the moment. A lot of the examples are not in this repo at all (which is why I'm closing this), you are likely better served by popping over to: https://github.com/sonatype/nexus-book-examples/tree/nexus-3.x/scripting
